module.exports = {
  rules: {
    'constructor-super': 2,
    'comma-dangle': [2, 'always-multiline'],
    'no-arrow-condition': 0,
    'no-cond-assign': [2, 'except-parens'],
    'no-console': 2,
    'no-debugger': 2,
    'no-alert': 2,
    'no-constant-condition': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-obj-calls': 2,
    'quote-props': [2, 'as-needed'],
    'no-sparse-arrays': 2,
    'no-undef': 2,
    'no-unreachable': 2,
    'no-unused-vars': 2,
    'no-use-before-define': 2,
    'use-isnan': 2,
    'block-scoped-var': 2,
  },
};
