module.exports = {
  plugins: [
    'react',
  ],
  rules: {
    'react/display-name': 0,
    'react/jsx-key': 2,
    'react/jsx-sort-prop-types': 0,
    'react/jsx-uses-react': 2,
    'react/no-did-mount-set-state': 2,
    'react/no-did-update-set-state': 2,
    'react/no-multi-comp': 0,
    'react/no-unknown-property': 2,
    'react/prefer-stateless-function': 2,
    'react/prop-types': 0,
    'react/react-in-jsx-scope': 2,
    'react/sort-comp': [2, {
      order: [
        'displayName',
        'propTypes',
        'contextTypes',
        'childContextTypes',
        'mixins',
        'statics',
        'defaultProps',
        'constructor',
        'getDefaultProps',
        'getInitialState',
        'state',
        'getChildContext',
        'componentWillMount',
        'componentDidMount',
        'componentWillReceiveProps',
        'shouldComponentUpdate',
        'componentWillUpdate',
        'componentDidUpdate',
        'componentWillUnmount',
        '/^on.+$/',
        '/^handle.+$/',
        '/^get.+$/',
        '/^update.+$/',
        'everything-else',
        '/^render.+$/',
        'render',
      ],
    }],
  },
};
